import { Product } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'zp-001',
    title: 'Royal Cotton Silk Jacquard Panjabi',
    category: 'Men',
    subCategory: 'Panjabi',
    basePrice: 3450,
    stitchingCharge: 750,
    description: 'Bespoke hand-tailored premium cotton-silk blend Panjabi with intricate Mandarin collar embroidery and concealed placket.',
    fabricType: 'Cotton Silk Jacquard',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=800',
    isCustomizable: true,
    isFeatured: true,
    stockStatus: 'In Stock',
    tags: ['Eid Collection', 'Wedding', 'Best Seller']
  },
  {
    id: 'zp-002',
    title: 'Imperial Dubaian Nida Abaya with Lace Trim',
    category: 'Women',
    subCategory: 'Abaya',
    basePrice: 4850,
    stitchingCharge: 950,
    description: 'Opulent Dubai Nida fabric Abaya featuring handcrafted scalloped lace cuffs and flowy silhouette custom tailored to your exact height.',
    fabricType: 'Original Dubai Nida',
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800',
    isCustomizable: true,
    isFeatured: true,
    stockStatus: 'In Stock',
    tags: ['Luxury', 'Modest Fashion', 'Dubai Import']
  },
  {
    id: 'zp-003',
    title: 'Bespoke Double-Breasted Italian Wool Suit',
    category: 'Men',
    subCategory: 'Suits',
    basePrice: 14500,
    stitchingCharge: 3500,
    description: 'Precision hand-cut 2-piece suit in Super 130s Italian wool. Crafted with canvas interior structure and peak lapels.',
    fabricType: 'Super 130s Italian Wool',
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&q=80&w=800',
    isCustomizable: true,
    isFeatured: true,
    stockStatus: 'In Stock',
    tags: ['Executive', 'Bespoke', 'Groom']
  },
  {
    id: 'zp-004',
    title: 'Zari Embroidered Designer Salwar Kameez',
    category: 'Women',
    subCategory: 'Salwar Kameez',
    basePrice: 6200,
    stitchingCharge: 1200,
    description: 'Exclusive organza dupattta with heavily zardozi embellished silk kameez. Customized sleeve styles and neckline cuts.',
    fabricType: 'Raw Silk & Pure Organza',
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&q=80&w=800',
    isCustomizable: true,
    isFeatured: true,
    stockStatus: 'In Stock',
    tags: ['Festive', 'Designer', 'Zardozi']
  },
  {
    id: 'zp-005',
    title: 'Classic White Soft Cotton Pajama / Trouser',
    category: 'Men',
    subCategory: 'Pajama',
    basePrice: 1100,
    stitchingCharge: 400,
    description: 'Ultra-breathable premium Egyptian cotton pajama tailored with elasticized drawstrings and deep side pockets.',
    fabricType: '100% Egyptian Cotton',
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=800',
    isCustomizable: true,
    isFeatured: false,
    stockStatus: 'In Stock',
    tags: ['Essential', 'Comfort']
  },
  {
    id: 'zp-006',
    title: 'Velvet Embellished Royal Waistcoat / Prince Coat',
    category: 'Men',
    subCategory: 'Waistcoats',
    basePrice: 4200,
    stitchingCharge: 1000,
    description: 'Rich maroon/black velvet waistcoat featuring custom antique brass buttons and sleek satin back panel.',
    fabricType: 'Micro Velvet & Satin',
    imageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800',
    isCustomizable: true,
    isFeatured: true,
    stockStatus: 'In Stock',
    tags: ['Groomswear', 'Velvet', 'Luxury']
  },
  {
    id: 'zp-007',
    title: 'Premium Linen Executive Formal Shirt',
    category: 'Men',
    subCategory: 'Formal Shirts',
    basePrice: 2200,
    stitchingCharge: 550,
    description: 'Crisp French cuff or button cuff formal shirt custom cut for razor-sharp shoulder lines and comfortable collar fit.',
    fabricType: 'Irish Pure Linen Cotton',
    imageUrl: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=800',
    isCustomizable: true,
    isFeatured: false,
    stockStatus: 'In Stock',
    tags: ['Office', 'Formal']
  },
  {
    id: 'zp-008',
    title: 'Black Modest Closed Borka with Belt',
    category: 'Women',
    subCategory: 'Borka',
    basePrice: 3900,
    stitchingCharge: 800,
    description: 'High-density wrinkle-free Zoom fabric Borka with metallic zipper details and optional waist cinching belt.',
    fabricType: 'Premium Zoom Fabric',
    imageUrl: 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?auto=format&fit=crop&q=80&w=800',
    isCustomizable: true,
    isFeatured: false,
    stockStatus: 'In Stock',
    tags: ['Modest', 'Daily Wear']
  },
  {
    id: 'zp-009',
    title: 'Royal Anarkali Evening Designer Gown',
    category: 'Women',
    subCategory: 'Designer Gowns',
    basePrice: 8900,
    stitchingCharge: 1800,
    description: 'Full flare 56-inch length designer gown with metallic hand work on bustier and flared georgette layers.',
    fabricType: 'Heavy Georgette & Shantoon',
    imageUrl: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&q=80&w=800',
    isCustomizable: true,
    isFeatured: true,
    stockStatus: 'In Stock',
    tags: ['Partywear', 'Gown', 'Exclusive']
  },
  {
    id: 'zp-010',
    title: 'Short Embroidered Summer Kurti',
    category: 'Women',
    subCategory: 'Kurtis',
    basePrice: 1850,
    stitchingCharge: 450,
    description: 'Lightweight linen kurti with delicate pastel floral neck embroidery and comfortable side slits.',
    fabricType: 'Breathable Slub Linen',
    imageUrl: 'https://images.unsplash.com/photo-1583391733975-d149c4021383?auto=format&fit=crop&q=80&w=800',
    isCustomizable: true,
    isFeatured: false,
    stockStatus: 'In Stock',
    tags: ['Casual', 'Summer']
  },
  {
    id: 'zp-011',
    title: 'Unstitched Premium Jamdani Weave Fabric (3 Piece)',
    category: 'Women',
    subCategory: 'Unstitched Fabrics',
    basePrice: 5500,
    stitchingCharge: 1100,
    description: 'Handspun authentic Bangladeshi Jamdani weave unstitched suit material with matching dupatta.',
    fabricType: 'Authentic Jamdani Cotton',
    imageUrl: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&q=80&w=800',
    isCustomizable: true,
    isFeatured: true,
    stockStatus: 'In Stock',
    tags: ['Heritage', 'Jamdani', 'Unstitched']
  },
  {
    id: 'zp-012',
    title: 'Traditional Kabli / Short Kurta Set',
    category: 'Men',
    subCategory: 'Kurta',
    basePrice: 2800,
    stitchingCharge: 600,
    description: 'Short length comfortable casual Kurta with mandarin collar and shoulder epaulettes.',
    fabricType: 'Wash & Wear Khadi',
    imageUrl: 'https://images.unsplash.com/photo-1597983073493-88cd35cfa3d0?auto=format&fit=crop&q=80&w=800',
    isCustomizable: true,
    isFeatured: false,
    stockStatus: 'In Stock',
    tags: ['Casual', 'Traditional']
  }
];
